[package]
name = "simfile"
version = "0.1.0"
edition = "2021"

[dependencies]
msd = "0.3.0"
serde = {version = "1.0.138", default-features = false}

[dev-dependencies]
claim = "0.5.0"
serde_test = "1.0.138"
tempdir = "0.3.7"
