[package]
name = "simfile"
version = "0.1.0"
edition = "2021"

[dependencies]
either = "1.7.0"
msd = "0.3.0"
serde = {version = "1.0.138", default-features = false}

[dev-dependencies]
serde_test = "1.0.138"
