[package]
name = "simfile"
version = "0.1.0"
edition = "2018"

[dependencies]
log = {version = "0.4.14", optional = true}

[dev-dependencies]
log = "0.4.14"
itertools = "0.10.1"
testing_logger = "0.1.1"
